---
  name: Pull Request Labeler
  
  on:
    pull_request_target:
  
  jobs:
    triage:
      name: Label triage
      permissions:
        contents: read
        pull-requests: write
        issues: write
      runs-on: ubuntu-latest
      steps:
        - uses: actions/labeler@v5
          with:
            sync-labels: true
        - uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const title = context.payload.pull_request.title.toLowerCase();
              const labels = [];
              
              if (title.includes('feat') || title.includes('feature')) {
                labels.push('feature');
              }
              
              if (title.includes('fix') || title.includes('bug')) {
                labels.push('bug');
              }
              
              if (title.includes('docs') || title.includes('documentation')) {
                labels.push('documentation');
              }

              if (title.includes('ci')) {
                labels.push('ci');
              }

              if (title.includes('aarch64')) {
                labels.push('aarch64');
              }

              if (title.includes('loongarch64')) {
                labels.push('loongarch64');
              }

              if (title.includes('riscv64')) {
                labels.push('riscv64');
              }

              if (title.includes('x86_64')) {
                labels.push('x86_64');
              }
                
              const pr_number = context.payload.pull_request?.number;

              if (pr_number && labels.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr_number,
                  labels: labels
                });
              }
            